# https://github.com/jcavat/docker-lamp
version: "3.1"
services:
    www:
        build: . # see ./Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mariadb:10.5
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: npress
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../data:/docker-entrypoint-initdb.d
#            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
